# Lighthouse CI Configuration
ci:
  collect:
    # ビルド済みの静的ファイルを配信
    staticDistDir: './dist'
    # 開発サーバーを起動（--silentで静かに）
    startServerCommand: 'node ./node_modules/http-server/bin/http-server ./dist -p 8080 --silent'
    # 計測対象URL
    url:
      - 'http://localhost:8080/index.html'
    # 各URLに対する実行回数
    numberOfRuns: 1
    # Chrome起動設定
    chromePath: null
    # Lighthouse設定
    settings:
      # デスクトップ設定
      preset: 'desktop'
      formFactor: 'desktop'
      # スロットリングを無効化（CI環境で安定させるため）
      throttlingMethod: 'provided'
      throttling:
        rttMs: 40
        throughputKbps: 10240
        cpuSlowdownMultiplier: 1
      # タイムアウト設定を大幅に延長
      maxWaitForLoad: 60000
      maxWaitForFcp: 30000
      pauseAfterFcpMs: 1000
      pauseAfterLoadMs: 1000
      # ネットワーク待機を短縮
      networkQuietThresholdMs: 1000
      cpuQuietThresholdMs: 1000
      # パフォーマンスのみ計測
      onlyCategories:
        - 'performance'
      # 不要な監査を大幅にスキップ
      skipAudits:
        - 'screenshot-thumbnails'
        - 'final-screenshot'
        - 'full-page-screenshot'
        - 'network-requests'
        - 'network-rtt'
        - 'network-server-latency'
        - 'uses-long-cache-ttl'
        - 'uses-optimized-images'
        - 'uses-text-compression'
        - 'uses-responsive-images'
        - 'offscreen-images'
        - 'render-blocking-resources'
        - 'unminified-css'
        - 'unminified-javascript'
        - 'unused-css-rules'
        - 'unused-javascript'
        - 'modern-image-formats'
        - 'uses-http2'
        - 'font-display'
        - 'third-party-summary'
        - 'third-party-facades'
        - 'largest-contentful-paint-element'
        - 'lcp-lazy-loaded'
        - 'layout-shifts'
        - 'long-tasks'
        - 'non-composited-animations'
        - 'unsized-images'
        - 'preload-lcp-image'
        - 'uses-rel-preconnect'
  
  # アサーション設定（非常に緩く）
  assert:
    assertions:
      'categories:performance':
        - 'warn'
        - minScore: 0.3
  
  # アップロード設定
  upload:
    target: 'filesystem'
    outputDir: './.lighthouseci'
